events {}

http {
    upstream user_service {
        server user-service:8000;
    }

    upstream item_service {
        server item-service:8000;
    }

    upstream swap_service {
        server swap-service:8000;
    }

    server {
        listen 80;

          # ---------- HEALTH  ----------
        location = /users/health {
            proxy_pass http://user_service/health;
        }

        location = /items/health {
            proxy_pass http://item_service/health;
        }

        location = /swap/health {
            proxy_pass http://swap_service/health;
        }

        # ---------- USERS ----------
        location /users {
            proxy_pass http://user_service;
        }

        # ---------- ITEMS ----------
        location /items {
            proxy_pass http://item_service;
        }

        # ---------- SWAP ----------
        location /swap {
            proxy_pass http://swap_service;
        }

        # ---------- ROOT ----------
        location / {
            return 200 "API Gateway running\n";
        }
    }
}